'use client';

import { useMemo } from 'react';
import { familyVolumeLabel } from '@/shared/utils/family-display';

function displaySkuCell(item: { sku?: string }): string {
  const s = String(item.sku || '').trim();
  return s || '—';
}

export interface InvoiceItem {
  qty: number;
  code: string;
  description: string;
  price: number;
  amount: number;
  sku?: string;
  familyId?: string;
  familyName?: string;
  familyCode?: string;
  familySku?: string;
  familyShortName?: string;
  familyVolume?: number;
  familyUnit?: string;
  familyInvoiceKey?: string;
  presentationLabel?: string;
  presentationGenericCode?: string;
}

function familyGroupKey(item: InvoiceItem): string {
  const fid = String(item.familyId || '').trim();
  if (fid) {
    const n = Number(fid);
    if (!Number.isNaN(n)) return `i:${n}`;
    return `i:${fid.toLowerCase()}`;
  }
  const fs = String(item.familySku || '').trim().toLowerCase();
  if (fs) return `s:${fs}`;
  const fc = String(item.familyCode || '').trim().toLowerCase();
  if (fc) return `c:${fc}`;
  const fn = String(item.familyName || '').trim().toLowerCase();
  return `n:${fn || '_'}`;
}

function familyInvoiceGroupKey(item: InvoiceItem): string {
  const pres = String(item.familyInvoiceKey || '').trim();
  if (pres) return pres;
  return [
    familyGroupKey(item),
    String(item.presentationGenericCode || '').trim().toLowerCase(),
    String(item.presentationLabel || '').trim().toLowerCase(),
    String(item.sku || '').trim().toLowerCase(),
    String(item.code || '').trim().toLowerCase(),
  ].join('\u0001');
}

export interface InvoiceProps {
  invoiceNumber: string;
  date: string;
  /** Route / vendor code (no seller name on the invoice). */
  vendorCode: string;
  storeName: string;
  storeAddress: string;
  items: InvoiceItem[];
  comments?: string;
  viewMode?: 'product' | 'family';
  printLayout?: 'normal' | 'ticket';
}

const L = {
  invoice: 'Invoice',
  date: 'Date',
  clientStore: 'Client / Store',
  vendor: 'Vendor',
  qty: 'Qty',
  code: 'Code',
  sku: 'SKU',
  description: 'Description',
  presentation: 'Presentation',
  unitPrice: 'Unit price',
  amount: 'Amount',
  totalUnits: 'Total units',
  total: 'Total',
  observations: 'Observations',
  footer: 'Document generated by Admin · Eternal Cosmetics, LLC',
  noFamily: 'No family',
  noItems: 'No items',
  itemLine: 'Item',
  familyLine: 'Family',
} as const;

const s = {
  white: '#ffffff',
  slate50: '#f8fafc',
  slate100: '#f1f5f9',
  slate200: '#e2e8f0',
  slate400: '#94a3b8',
  slate500: '#64748b',
  slate600: '#475569',
  slate700: '#334155',
  slate800: '#1e293b',
  slate900: '#0f172a',
} as const;

export function Invoice({
  invoiceNumber,
  date,
  vendorCode,
  storeName,
  storeAddress,
  items,
  comments,
  viewMode = 'product',
  printLayout = 'normal',
}: InvoiceProps) {
  const productRows = useMemo(() => {
    const byKey = new Map<string, InvoiceItem & { qty: number; amount: number }>();
    items.forEach((it) => {
      const skuKey = displaySkuCell(it);
      const desc = String(it.description || '').trim();
      const price = Number(it.price) || 0;
      const key = `${skuKey}||${desc}||${price}`;
      if (!byKey.has(key)) {
        byKey.set(key, { ...it, qty: 0, amount: 0 });
      }
      const row = byKey.get(key)!;
      row.qty += Number(it.qty) || 0;
      row.amount += Number(it.amount) || 0;
      if (!String(row.sku || '').trim() && String(it.sku || '').trim()) row.sku = it.sku;
    });
    return [...byKey.values()].filter((x) => x.qty !== 0 || x.amount !== 0);
  }, [items]);
  const totalPcs = items.reduce((sum, item) => sum + item.qty, 0);
  const totalAmount = items.reduce((sum, item) => sum + item.amount, 0);

  const familyRows = useMemo(() => {
    const byKey = new Map<
      string,
      {
        code: string;
        presentationDesc: string;
        qty: number;
        amount: number;
      }
    >();
    items.forEach((it) => {
      const familyName = String(it.familyName || '').trim() || L.noFamily;
      const familyCode = String(it.familyCode || '').trim();
      const presGen = String(it.presentationGenericCode || '').trim();
      const key = familyInvoiceGroupKey(it);
      const vol = familyVolumeLabel(it.familyVolume, it.familyUnit);
      const short = String(it.familyShortName || '').trim();
      const presLine =
        String(it.presentationLabel || '').trim() ||
        [short, vol].filter(Boolean).join(' · ') ||
        familyName;
      if (!byKey.has(key)) {
        byKey.set(key, {
          code: presGen || familyCode || '—',
          presentationDesc: presLine,
          qty: 0,
          amount: 0,
        });
      }
      const row = byKey.get(key)!;
      if ((!row.code || row.code === '—') && presGen) row.code = presGen;
      else if ((!row.code || row.code === '—') && familyCode) row.code = familyCode;
      if (!row.presentationDesc || row.presentationDesc === L.noFamily) row.presentationDesc = presLine;
      row.qty += Number(it.qty) || 0;
      row.amount += Number(it.amount) || 0;
    });
    return [...byKey.values()]
      .map((r) => ({
        ...r,
        price: r.qty > 0 ? r.amount / r.qty : 0,
      }))
      .sort((a, b) => b.qty - a.qty || b.amount - a.amount);
  }, [items]);

  const vendorDisplay = String(vendorCode || '').trim() || '—';

  if (printLayout === 'ticket') {
    const rows =
      viewMode === 'family'
        ? familyRows.map((r) => ({
            left: `${r.code || '—'} ${r.presentationDesc || ''}`.trim(),
            qty: r.qty,
            price: r.price,
            amount: r.amount,
          }))
        : productRows.map((it) => ({
            left: `${displaySkuCell(it)} ${it.description || ''}`.trim(),
            qty: Number(it.qty) || 0,
            price: Number(it.price) || 0,
            amount: Number(it.amount) || 0,
          }));

    const ticketUnits = rows.reduce((sAcc, r) => sAcc + (Number(r.qty) || 0), 0);
    const ticketTotal = rows.reduce((sAcc, r) => sAcc + (Number(r.amount) || 0), 0);
    const ticketStore = String(storeName || '').trim() || '—';

    return (
      <>
        <style>{`
          @media print {
            #invoice-print.ticket-print {
              width: 58mm !important;
              max-width: 58mm !important;
              margin: 0 auto !important;
              box-shadow: none !important;
              border: 0 !important;
            }
          }
        `}</style>
        <div id="invoice-print" className="ticket-print bg-white text-black" style={{ fontFamily: 'monospace', fontSize: 11, padding: 6 }}>
          <div style={{ textAlign: 'center', marginBottom: 6 }}>
            <div style={{ fontWeight: 700 }}>ETERNAL COSMETICS</div>
            <div>{invoiceNumber || '—'}</div>
            <div>{date}</div>
          </div>
          <div style={{ marginBottom: 4 }}>
            <div>
              <strong>STORE:</strong> {ticketStore}
            </div>
            <div>
              <strong>VENDOR:</strong> {vendorDisplay}
            </div>
          </div>
          <div style={{ borderTop: '1px dashed #000', margin: '4px 0' }} />
          <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 700 }}>
            <span>{viewMode === 'family' ? L.familyLine : L.itemLine}</span>
            <span>QTY / AMT</span>
          </div>
          <div style={{ borderTop: '1px dashed #000', margin: '4px 0' }} />
          {rows.map((r, i) => (
            <div key={i} style={{ marginBottom: 4 }}>
              <div style={{ whiteSpace: 'normal', wordBreak: 'break-word' }}>{r.left}</div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 10 }}>
                <span>
                  x{r.qty} @ ${Number(r.price).toFixed(2)}
                </span>
                <span>${Number(r.amount).toFixed(2)}</span>
              </div>
            </div>
          ))}
          <div style={{ borderTop: '1px dashed #000', margin: '6px 0' }} />
          <div style={{ display: 'flex', justifyContent: 'space-between' }}>
            <span>{L.totalUnits}</span>
            <strong>{ticketUnits}</strong>
          </div>
          <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 700 }}>
            <span>{L.total}</span>
            <span>${ticketTotal.toFixed(2)}</span>
          </div>
        </div>
      </>
    );
  }

  return (
    <>
      <style>{`
        #invoice-print tbody tr:hover { background-color: rgba(248, 250, 252, 0.5); }
        @media print {
          #invoice-print {
            box-shadow: none !important;
            max-width: none !important;
            overflow: visible !important;
            page-break-inside: auto;
          }
          #invoice-print .invoice-inner {
            max-width: none !important;
            padding: 1rem 1.5rem 2rem !important;
          }
          #invoice-print .invoice-table-wrap {
            overflow: visible !important;
          }
        }
      `}</style>
      <div
        id="invoice-print"
        style={{
          backgroundColor: s.white,
          color: s.slate800,
          maxWidth: '100%',
          width: '100%',
          margin: 0,
          boxShadow: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
          fontFamily: 'ui-sans-serif, system-ui, sans-serif',
        }}
        className="print:shadow-none"
      >
        <div
          className="invoice-inner md:!px-12 md:!py-14"
          style={{ padding: '2.5rem 2.5rem 3.5rem 2.5rem', maxWidth: '48rem', marginLeft: 'auto', marginRight: 'auto' }}
        >
          <div
            style={{
              borderBottomWidth: 2,
              borderBottomStyle: 'solid',
              borderBottomColor: s.slate800,
              paddingBottom: '2rem',
              marginBottom: '2.5rem',
            }}
          >
            <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between" style={{ gap: '2rem' }}>
              <div style={{ flexShrink: 0 }}>
                <p
                  style={{
                    fontSize: '10px',
                    fontWeight: 600,
                    color: s.slate500,
                    letterSpacing: '0.2em',
                    marginBottom: '0.25rem',
                    textTransform: 'uppercase',
                  }}
                >
                  Eternal Cosmetics
                </p>
                <h1
                  style={{
                    fontSize: '1.5rem',
                    fontWeight: 700,
                    color: s.slate900,
                    letterSpacing: '-0.025em',
                    lineHeight: 1.25,
                  }}
                >
                  ETERNAL COSMETICS, LLC
                </h1>
                <p style={{ fontSize: '0.875rem', color: s.slate600, marginTop: '0.5rem' }}>7NW 84TH ST, MIAMI, FL 33166</p>
                <p style={{ fontSize: '0.875rem', color: s.slate600 }}>TEL: (305) 12345678</p>
              </div>
              <div
                style={{
                  flex: 1,
                  minWidth: 0,
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'flex-end',
                  paddingRight: '1rem',
                  marginLeft: 'auto',
                }}
                className="sm:text-right"
              >
                <div
                  style={{
                    display: 'inline-block',
                    padding: '0.25rem 0.75rem',
                    backgroundColor: s.slate900,
                    color: s.white,
                    fontSize: '0.75rem',
                    fontWeight: 600,
                    letterSpacing: '0.05em',
                    textTransform: 'uppercase',
                    borderRadius: '2px',
                  }}
                >
                  {L.invoice}
                </div>
                <p style={{ fontSize: '0.875rem', fontWeight: 500, color: s.slate900, marginTop: '0.75rem' }}>{invoiceNumber || '—'}</p>
                <p style={{ fontSize: '0.875rem', color: s.slate600 }}>
                  {L.date}: {date}
                </p>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-2" style={{ gap: '8.5rem', marginBottom: '3.5rem' }}>
            <div>
              <p
                style={{
                  fontSize: '11px',
                  fontWeight: 600,
                  color: s.slate500,
                  letterSpacing: '0.05em',
                  marginBottom: '0.5rem',
                  textTransform: 'uppercase',
                }}
              >
                {L.clientStore}
              </p>
              <p style={{ fontSize: '0.875rem', fontWeight: 600, color: s.slate900 }}>{storeName || '—'}</p>
            </div>
            <div>
              <p
                style={{
                  fontSize: '11px',
                  fontWeight: 600,
                  color: s.slate500,
                  letterSpacing: '0.05em',
                  marginBottom: '0.5rem',
                  textTransform: 'uppercase',
                }}
              >
                {L.vendor}
              </p>
              <p style={{ fontSize: '0.875rem', fontWeight: 600, color: s.slate900 }}>{vendorDisplay}</p>
            </div>
          </div>

          <div
            className="invoice-table-wrap"
            style={{ overflow: 'hidden', border: `1px solid ${s.slate200}`, marginBottom: '2.5rem' }}
          >
            <table style={{ width: '100%', fontSize: '0.875rem', borderCollapse: 'collapse' }}>
              <thead>
                {viewMode === 'product' ? (
                  <tr style={{ backgroundColor: s.slate800, color: s.white }}>
                    <th style={{ padding: '1rem 2rem', fontWeight: 600, textAlign: 'center', width: '3.5rem' }}>{L.qty}</th>
                    <th style={{ padding: '1rem 2rem', fontWeight: 600, textAlign: 'left', width: '6rem' }}>{L.sku}</th>
                    <th style={{ padding: '1rem 2rem', fontWeight: 600, textAlign: 'left' }}>{L.description}</th>
                    <th style={{ padding: '1rem 2rem', fontWeight: 600, textAlign: 'right', width: '6rem' }}>{L.unitPrice}</th>
                    <th style={{ padding: '1rem 2rem', fontWeight: 600, textAlign: 'right', width: '7rem' }}>{L.amount}</th>
                  </tr>
                ) : (
                  <tr style={{ backgroundColor: s.slate800, color: s.white }}>
                    <th style={{ padding: '1rem 2rem', fontWeight: 600, textAlign: 'center', width: '3.5rem' }}>{L.qty}</th>
                    <th style={{ padding: '1rem 2rem', fontWeight: 600, textAlign: 'left', width: '6rem' }}>{L.code}</th>
                    <th style={{ padding: '1rem 2rem', fontWeight: 600, textAlign: 'left' }}>{L.presentation}</th>
                    <th style={{ padding: '1rem 2rem', fontWeight: 600, textAlign: 'right', width: '6rem' }}>{L.unitPrice}</th>
                    <th style={{ padding: '1rem 2rem', fontWeight: 600, textAlign: 'right', width: '7rem' }}>{L.amount}</th>
                  </tr>
                )}
              </thead>
              <tbody>
                {viewMode === 'product'
                  ? productRows.map((item, index) => (
                      <tr
                        key={index}
                        style={{
                          borderBottom: index < productRows.length - 1 ? `1px solid ${s.slate100}` : undefined,
                        }}
                      >
                        <td style={{ padding: '1rem 2rem', textAlign: 'center', color: s.slate700 }}>{item.qty}</td>
                        <td style={{ padding: '1rem 2rem', color: s.slate700 }}>{displaySkuCell(item)}</td>
                        <td style={{ padding: '1rem 2rem', color: s.slate900 }}>{item.description || '—'}</td>
                        <td style={{ padding: '1rem 2rem', textAlign: 'right', color: s.slate700 }}>${Number(item.price).toFixed(2)}</td>
                        <td style={{ padding: '1rem 2rem', textAlign: 'right', fontWeight: 500, color: s.slate900 }}>
                          ${Number(item.amount).toFixed(2)}
                        </td>
                      </tr>
                    ))
                  : familyRows.map((item, index) => (
                      <tr
                        key={`f-${index}`}
                        style={{
                          borderBottom: index < familyRows.length - 1 ? `1px solid ${s.slate100}` : undefined,
                        }}
                      >
                        <td style={{ padding: '1rem 2rem', textAlign: 'center', color: s.slate700 }}>{item.qty}</td>
                        <td style={{ padding: '1rem 2rem', color: s.slate700 }}>{item.code || '—'}</td>
                        <td style={{ padding: '1rem 2rem', color: s.slate900 }}>{item.presentationDesc || '—'}</td>
                        <td style={{ padding: '1rem 2rem', textAlign: 'right', color: s.slate700 }}>${Number(item.price).toFixed(2)}</td>
                        <td style={{ padding: '1rem 2rem', textAlign: 'right', fontWeight: 500, color: s.slate900 }}>
                          ${Number(item.amount).toFixed(2)}
                        </td>
                      </tr>
                    ))}
                {(viewMode === 'product' ? productRows.length === 0 : familyRows.length === 0) && (
                  <tr>
                    <td colSpan={5} style={{ padding: '2rem 1rem', textAlign: 'center', color: s.slate400, fontSize: '0.875rem' }}>
                      {L.noItems}
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '2rem' }}>
            <div
              style={{
                width: '16rem',
                borderTopWidth: 2,
                borderTopStyle: 'solid',
                borderTopColor: s.slate200,
                paddingTop: '1rem',
              }}
            >
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.875rem', marginBottom: '0.25rem' }}>
                <span style={{ color: s.slate600 }}>{L.totalUnits}</span>
                <span style={{ fontWeight: 500, color: s.slate800 }}>{totalPcs}</span>
              </div>
              <div
                style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  fontSize: '1.125rem',
                  fontWeight: 700,
                  color: s.slate900,
                  marginTop: '0.75rem',
                  paddingTop: '0.5rem',
                  borderTop: `1px solid ${s.slate100}`,
                }}
              >
                <span>{L.total}</span>
                <span>${totalAmount.toFixed(2)}</span>
              </div>
            </div>
          </div>

          {comments && (
            <div
              style={{
                marginTop: '2rem',
                paddingTop: '1.5rem',
                borderTop: `1px solid ${s.slate200}`,
              }}
            >
              <p
                style={{
                  fontSize: '11px',
                  fontWeight: 600,
                  color: s.slate500,
                  letterSpacing: '0.05em',
                  marginBottom: '0.5rem',
                  textTransform: 'uppercase',
                }}
              >
                {L.observations}
              </p>
              <p style={{ fontSize: '0.875rem', color: s.slate700 }}>{comments}</p>
            </div>
          )}

          <div
            style={{
              marginTop: '2.5rem',
              paddingTop: '1rem',
              borderTop: `1px solid ${s.slate100}`,
              textAlign: 'center',
            }}
          >
            <p
              style={{
                fontSize: '10px',
                color: s.slate400,
                letterSpacing: '0.05em',
                textTransform: 'uppercase',
              }}
            >
              {L.footer}
            </p>
          </div>
        </div>
      </div>
    </>
  );
}
